[project]
name = "weather-app-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "marjon", email = "marjongodito@gmanmi.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.142.2",
    "python-dotenv>=1.2.4",
    "simple-mongo-2>=2.0.0",
]

[project.scripts]
weather-app-api = "weather_app_api:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
